### ISSUE TITLE
Error loading GPU renderer (GT: 0.00 GHz) even when satisfying the configuration checklist

### ISSUE THREAD

**Issue by iamsteven1995** [vit9696/Shiki#10]
Thanks for your work in advance. I cannot acquire hardware decode and would like to ask for your help.

GPU:
Intel i5-6500 (HD530), NVIDIA GTX1060

Pre-requisite:
1. Renamed GFX0 to IGPU, injected Intel with 0x19120001 (connector-less)
2. IOVARendererID presented under nvAccelerator (under PEG0@1 → IOPP → GFX0@0)
3. GVA info: Successfully connected to the Intel plugin, offline Gen9 (followed by AVDCreateGPUAccelerator: Error loading GPU renderer VDADecoderCreate failed. err: -12473)
4. IMEI presented
5. No overrides
6. Mac model as iMac17,1 (Board-ID: Mac-DB15BD556843C820)
7. Have shikigva=4 in boot flags (Lily 1.2, NvidiaGraphicsFixup 1.2, Shiki 2.1)

Problem:
GT: 0.00 GHz in Intel Power Gadget
VDADecoderChecker returned:
GVA info: Successfully connected to the Intel plugin, offline Gen9 
AVDCreateGPUAccelerator: Error loading GPU renderer
VDADecoderCreate failed. err: -12473
An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process.
VDADecoderCreate failed. err: -12473

Would you please point me some directions in enabling QuickSync for my hackintosh?

Attachment:
[iMac.ioreg](https://drive.google.com/open?id=0B7TdueMA3RIzc0EyZXJRT1FpUjA)
[EFI](https://drive.google.com/open?id=0B7TdueMA3RIzSEtHWTZoRDVKRkU)

**Comment by vit9696** [comment]
Hi, well, such an error happens when Shiki fails to patch AppleGVA.framework to enable NVIDIA compatibility (that's what `shikigva=4` does). To prove it you could replace it manually and see if it fixes things.

Before that, however, I would like you to try running VDADecoderChecker in 3 different ways and post all the output you get here:
```
DYLD_PREBIND_DEBUG=1 DYLD_SHARED_CACHE_DONT_VALIDATE=1 /path/to/vdadecoderchecker
DYLD_PREBIND_DEBUG=1 /path/to/vdadecoderchecker
DYLD_PREBIND_DEBUG=1 DYLD_SHARED_REGION=avoid /path/to/vdadecoderchecker
```

If at least one of the commands prints that hardware acceleration is fully supported, it is probably worth stopping at that point. Otherwise do the following steps to check with manually patched AppleGVA:

1. Disable Lilu and all the plugins (this is just in case, it should not be really necessary but better to do it).
2. Download a patched [AppleGVA.framework](https://s3-eu-west-1.amazonaws.com/i.applelife.ru/2017/10/280347_aa53983f9fe3904898c3b33964ab5818.zip) for 10.12.6
3. Install it
```
sudo su
cd /System/Library/PrivateFrameworks/
mv AppleGVA.framework AppleGVA.framework.org
unzip -q /path/to/AppleGVA.framework.org.zip
codesign --deep -fs - AppleGVA.framework
chown -R root:wheel AppleGVA.framework
chmod -R 755 AppleGVA.framework
update_dyld_shared_cache -force
reboot
```
4. Reenable Lilu with the plugins and see if it fixed things for you

Most likely it will work, so the only thing to do will be to restore the original AppleGVA.framework and understand why it does not get patched dynamically. Unfortunately it is not an easy task, since many system issues (for example, the most common case is a corrupted/missing dyld shared cache or broken signature) will lead to this.

**Comment by iamsteven1995** [comment]
Thanks for you quick feedback! I did the testings as stated and got the following results:
1. DYLD_PREBIND_DEBUG=1 DYLD_SHARED_CACHE_DONT_VALIDATE=1 /path/to/vdadecoderchecker
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/VideoDecodeAcceleration.framework/Versions/A/VideoDecodeAcceleration
dyld: image not prebound, so could not use prebinding in /Users/kctsangab/Documents/Hackintosh/VDADecoderChecker
dyld: image not prebound, so could not use prebinding in /System/Library/Extensions/AppleIntelSKLGraphicsVADriver.bundle/Contents/MacOS/AppleIntelSKLGraphicsVADriver
GVA info: Successfully connected to the Intel plugin, offline Gen9 
dyld: image not prebound, so could not use prebinding in /System/Library/Extensions/GeForceVADriverWeb.bundle/Contents/MacOS/GeForceVADriverWeb
AVDCreateGPUAccelerator: Error loading GPU renderer
VDADecoderCreate failed. err: -12473
An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process.
VDADecoderCreate failed. err: -12473

2. DYLD_PREBIND_DEBUG=1 /path/to/vdadecoderchecker
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/VideoDecodeAcceleration.framework/Versions/A/VideoDecodeAcceleration
dyld: image not prebound, so could not use prebinding in /Users/kctsangab/Documents/Hackintosh/VDADecoderChecker
dyld: image not prebound, so could not use prebinding in /System/Library/Extensions/AppleIntelSKLGraphicsVADriver.bundle/Contents/MacOS/AppleIntelSKLGraphicsVADriver
GVA info: Successfully connected to the Intel plugin, offline Gen9 
dyld: image not prebound, so could not use prebinding in /System/Library/Extensions/GeForceVADriverWeb.bundle/Contents/MacOS/GeForceVADriverWeb
AVDCreateGPUAccelerator: Error loading GPU renderer
VDADecoderCreate failed. err: -12473
An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process.
VDADecoderCreate failed. err: -12473

3. DYLD_PREBIND_DEBUG=1 DYLD_SHARED_REGION=avoid /path/to/vdadecoderchecker
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_kernel.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_m.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_blocks.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libc++abi.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libc++.1.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libobjc.A.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libdispatch.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_sandbox.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libmacho.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_notify.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_symptoms.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_trace.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_dnssd.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libcorecrypto.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libcommonCrypto.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_networkextension.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_configuration.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_network.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_info.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_asl.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libxpc.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/liblaunch.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_c.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libkeymgr.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libunwind.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libcompiler_rt.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_malloc.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libdyld.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_platform.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_pthread.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libcache.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libquarantine.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libcopyfile.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libremovefile.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_coreservices.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_coretls.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libsystem_secinit.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libSystem.B.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libenergytrace.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libbsm.0.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libDiagnosticMessagesClient.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libicucore.A.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libz.1.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
dyld: image not prebound, so could not use prebinding in /usr/lib/system/libkxld.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
dyld: image not prebound, so could not use prebinding in /usr/lib/libauto.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libpcap.A.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libcoretls.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libOpenScriptingUtil.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libpam.2.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libsqlite3.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libbz2.1.0.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/liblzma.5.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libxml2.2.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libxar.1.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Security.framework/Versions/A/Security
dyld: image not prebound, so could not use prebinding in /usr/lib/libcoretls_cfhelpers.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libnetwork.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
dyld: image not prebound, so could not use prebinding in /usr/lib/libarchive.2.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/liblangid.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libCRFSuite.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
dyld: image not prebound, so could not use prebinding in /usr/lib/libiconv.2.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libcmph.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
dyld: image not prebound, so could not use prebinding in /usr/lib/libmarisa.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libChineseTokenizer.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libcompression.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
dyld: image not prebound, so could not use prebinding in /usr/lib/libmecabra.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
dyld: image not prebound, so could not use prebinding in /usr/lib/libxslt.1.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSync.framework/Versions/A/ColorSync
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
dyld: image not prebound, so could not use prebinding in /usr/lib/libheimdal-asn1.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libresolv.9.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/GSS.framework/Versions/A/GSS
dyld: image not prebound, so could not use prebinding in /usr/lib/libcups.2.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/GPUCompiler.framework/libmetal_timestamp.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/Metal.framework/Versions/A/Metal
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
dyld: image not prebound, so could not use prebinding in /usr/lib/libdscsym.dylib
dyld: image not prebound, so could not use prebinding in /usr/lib/libspindump.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/VideoDecodeAcceleration.framework/Versions/A/VideoDecodeAcceleration
dyld: image not prebound, so could not use prebinding in /Users/kctsangab/Documents/Hackintosh/VDADecoderChecker
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/AppleGVA.framework/AppleGVA
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
dyld: image not prebound, so could not use prebinding in /usr/lib/libFosl_dynamic.dylib
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
dyld: image not prebound, so could not use prebinding in /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
dyld: image not prebound, so could not use prebinding in /System/Library/PrivateFrameworks/SkyLight.framework/SkyLight
dyld: image not prebound, so could not use prebinding in /System/Library/Extensions/AppleIntelSKLGraphicsVADriver.bundle/Contents/MacOS/AppleIntelSKLGraphicsVADriver
GVA info: Successfully connected to the Intel plugin, offline Gen9 
dyld: image not prebound, so could not use prebinding in /System/Library/Extensions/GeForceVADriverWeb.bundle/Contents/MacOS/GeForceVADriverWeb
dyld: image not prebound, so could not use prebinding in /System/Library/Extensions/AppleIntelSKLGraphicsVAME.bundle/Contents/MacOS/AppleIntelSKLGraphicsVAME
Hardware acceleration is fully supported

For the third test, it does stated "Hardware acceleration is fully supported".
Does it mean I can try the patched AppleGVA provided by you?

Once again, thanks for your work and help.

**Comment by vit9696** [comment]
Ok, I understand what is going wrong now. Unlike CoreFP AppleGVA resides in shared cache, and a patch applied to it does not reach all the apps but only select ones (iTunes and QuickTime by default). A proper fix will require a broader research in Lilu user patcher, which I am not going to do for 1.2.0 for stability reasons.

As for now there could be 3 workarounds:
1. Use a patched AppleGVA.framework, that will work, though it is a rather undesired solution (since you have to disassemble each AppleGVA.framework received from OS update and patch it differently all the time)
2. Launch the software you need via terminal like this:
```
DYLD_SHARED_REGION=avoid /path/to/program.app/Contents/MacOS/program
```
3. Have most common software added to Shiki, so that it patches it automatically until a proper solution is implemented. This one is probably not so bad, but you need to tell me the software you need with absolute paths to executables.

**Comment by iamsteven1995** [comment]
Thanks for the workarounds! I accidentally found it working by force updating dyld_shared_cache (sudo update_dyld_shared_cache -force). After rebooting, VDADecoderChecker produced the following result:

GVA info: Successfully connected to the Intel plugin, offline Gen9 
Hardware acceleration is fully supported

I believe hardware acceleration is somehow working right now (tested with IINA). However, streaming videos from Apple Music still doesn't work and it breaks Netflix video. I will try the workarounds you provided and run more testings.

**Comment by vit9696** [comment]
Alright, I guess I will close it for now then.

**Comment by unrealwzg** [comment]
I have the exactly same issue, unfortunately updating dyld_shared_cache does not work for me, I need to replace a patched AppleGVA.framework
