### ISSUE TITLE
iTunes crash on DRM protected films

### ISSUE THREAD

**Issue by barijaona** [vit9696/Shiki#11]
Testing macOS High Sierra with Shiki 2.1.0, Lilu 1.2.0, NvidiaGraphicsFixup 1.2.0
boot argument shikigva=12 to enable hardware encoding

I experience crash while trying to read a film on iTunes. Attached is crashlog.
[iTunes_2017-10-12-043311_iMac.crash.zip](https://github.com/vit9696/Shiki/files/1377817/iTunes_2017-10-12-043311_iMac.crash.zip)

Other configuration details [can be seen here](https://github.com/barijaona/CLOVER_GA-Z170X-Gaming5).

**Comment by vit9696** [comment]
Hi. Not much we could do here, Apple's bug unfortunately. You could try standard ways mentioned in the FAQ, but I don't think it will help. See https://github.com/vit9696/Lilu/issues/20.

**Comment by Dids** [comment]
FYI, I was also seeing this, but repairing permissions as stated here fixed it, although not entirely sure why: https://support.apple.com/en-us/HT203538
