### ISSUE TITLE
No Hardware Decoding

### ISSUE THREAD

**Issue by esetnik** [vit9696/Shiki#12]
GPU:
Intel i7-7700k (HD630), NVIDIA GTX1080TI

Renamed GFX0 to IGPU, injected Intel with 0x59120003 (connector-less)
IOVARendererID presented under nvAccelerator (under PEG0@1 → IOPP → GFX0@0)
GVA info:
```
GVA info: Successfully connected to the Intel plugin, offline Gen95 
AVDCreateGPUAccelerator: Error loading GPU renderer
VDADecoderCreate failed. err: -12473
An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process.
VDADecoderCreate failed. err: -12473
```

No overrides
Mac model as iMac18,3 (Board-ID: Mac-BE088AF8C5EB4FA2)
```
		<key>Mac-BE088AF8C5EB4FA2</key>
		<dict>
			<key>facetimeDecode</key>
			<true/>
			<key>forceOfflineRenderer</key>
			<true/>
			<key>hwe</key>
			<true/>
			<key>hweBGRA</key>
			<true/>
			<key>ke1</key>
			<true/>
			<key>pp</key>
			<true/>
		</dict>
```
Have shikigva=12 in boot flags (Lilu 1.2.1, NvidiaGraphicsFixup 1.2, Shiki 2.1.2)

I think it could be the same issue as https://github.com/vit9696/Shiki/issues/10 but I don't know enough so I opened a separate ticket.

Further debugging:
```
~
❯ DYLD_PREBIND_DEBUG=1 DYLD_SHARED_CACHE_DONT_VALIDATE=1 ~/Downloads/VDADecoderCheckerSierra
dyld: warning, unknown environment variable: DYLD_SHARED_CACHE_DONT_VALIDATE
dyld: image not prebound, so could not use prebinding in /Users/ethan/Downloads/VDADecoderCheckerSierra
dyld: image not prebound, so could not use prebinding in /Library/GPUBundles/GeForceMTLDriverWeb.bundle/Contents/MacOS/GeForceMTLDriverWeb
dyld: image not prebound, so could not use prebinding in /System/Library/Extensions/AppleIntelKBLGraphicsVADriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsVADriver
GVA info: Successfully connected to the Intel plugin, offline Gen95
dyld: image not prebound, so could not use prebinding in /Library/GPUBundles/GeForceVADriverWeb.bundle/Contents/MacOS/GeForceVADriverWeb
AVDCreateGPUAccelerator: Error loading GPU renderer
VDADecoderCreate failed. err: -12473
An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process.
VDADecoderCreate failed. err: -12473
```

**Comment by vit9696** [comment]
Hi, due to hardware acceleration supported on 10.13 as a mere hack it is enabled on per-process basis based on their names. VDADecoderChecker is OK, but VDADecoderCheckerSierra is not in the list. You could check the names in Patches.plist in this repo.

**Comment by esetnik** [comment]
Oh that’s a good point. I actually knew it was per process on HS but I forgot that the download for VDADecoderChecker is different from the patches. I will rename and test this. Thanks!

**Comment by esetnik** [comment]
Unfortunately I still have the same issue after renaming VDADecoderChecker.

```
❯ /Applications/VDADecoderChecker ; exit;
GVA info: Successfully connected to the Intel plugin, offline Gen95 
AVDCreateGPUAccelerator: Error loading GPU renderer
VDADecoderCreate failed. err: -12473
An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process.
VDADecoderCreate failed. err: -12473

[Process completed]
```

Also, not sure if this is related, but when I use NvidiaGraphicsFixup.kext in my system I see:
`Hardware encoding Supported: NO` in MacX Video Converter Pro. When removing NvidiaGraphicsFixup I see `Hardware Encoding Supported: YES`. So it seems that injection of IOVARendererID in nvAccelerator (or some other aspect of NvidiaGraphicsFixup causes Quick Sync issues whereas removal fixes them. Is it easy to patch IOVARendererID without NvidiaGraphicsFixup or is it best to try to achieve working hardware encoding / decoding with NvidiaGraphcisFixup present?

**Comment by esetnik** [comment]
I did some further digging and found a related thread that mentions the loss of Quick Sync when using IOVARendererID injection through NvidiaGraphicsFixup. I was able to confirm that I am able to get Quick Sync back with `shikivga=12,ngfxpatch=pikera,-ngfxnovarenderer` but I still have the same error from VDADecoderChecker leaving me unsure whether hardware decoding is working properly. See https://sourceforge.net/p/nvidiagraphicsfixup/tickets/3/ for further info.

Is there anything else I can provide you @vit9696 to aid in debugging?

**Comment by vit9696** [comment]
Now that you said it I realised that you have iMac18,3 model. And this model does not have `forceBoostOff` in Info.plist. This property is required for nvidia from what I remember. Make an AppleGVA.framework backup and add it with true value.

If it works, will see what I can do to make it work without file invasion. You are the second person asking for `forceBoostOff`...

**Comment by esetnik** [comment]
@vit9696 I attempted using your patched Shiki framework. How can I confirm whether or not it properly added `forceBoostOff`? I still have the same error from VDADecoderChecker.

**Comment by vit9696** [comment]
I do not think there is a way without running a debugger, if you still have an error it is worth trying to patch AppleGVA.framework itself or change your macmodel to NVIDIA e.g. iMac14,2.
I could inagine myself forgetting to make a target list for the chane in the uploaded kext.

**Comment by esetnik** [comment]
After manually patching AppleGVA.framework and reverting to Shiki 2.1.2 (built myself) I get VDADecoderChecker pass.

```
❯ /Applications/VDADecoderChecker ; exit;
GVA info: Successfully connected to the Intel plugin, offline Gen95 
Hardware acceleration is fully supported

[Process completed]
```

So I guess we need to upgrade your patch to include iMac18,3 in the target list.

**Comment by vit9696** [comment]
Egh, I rechecked everything and it is very strange. I uploaded the latest sources of Shiki to github. Please make a debug log with Shiki and Lilu with `shikigva=48` (`-shikidbg -liludbg`). To be honest, I expected it to work just fine. Also, it may well be a good idea to try 10.12 with the same configuration.
If you are familiar with debugging, I guess you could try running VDADecoderChecker and see if `forceBoostOff` in AppleGVA.framework is replaced with `ke1`. If not… we could try to make something up…

**Comment by esetnik** [comment]
Using https://github.com/vit9696/Shiki/commit/92a0f39acfbac5a06b1b4ebcdfb22955e92011cd with`shikigva=48 -shikidbg -liludbg` I get VDADecoderChecker failure. Seems to be the same as with unpatched AppleGVA.framework.

Attached logs as requested. Anything else I can do to help? 
[shiki.log](https://github.com/vit9696/Shiki/files/1489061/shiki.log)

If you are familiar with debugging, I guess you could try running VDADecoderChecker and see if forceBoostOff in AppleGVA.framework is replaced with ke1
Not really sure where to get started with that request. Run VDADecoderChecker in debug on Xcode?

**Comment by esetnik** [comment]
Actually maybe I didn't understand. I just checked `/System/Library/PrivateExtensions/AppleGVA.framework/Resources/Info.plist` and 

```
                <key>Mac-BE088AF8C5EB4FA2</key>
                <dict>
                        <key>facetimeDecode</key>
                        <true/>
                        <key>forceOfflineRenderer</key>
                        <true/>
                        <key>forceBoostOff</key>
                        <true/>
                        <key>hwe</key>
                        <true/>
                        <key>hweBGRA</key>
                        <true/>
                        <key>ke1</key>
                        <true/>
                        <key>pp</key>
                        <true/>
                </dict>
```

So it looks like injection did occur but VDADecoderChecker fails without manual patching.

**Comment by vit9696** [comment]
I checked the debug log and saw nothing. Did you even attempt to run VDADecoderChecker before saving the log? It is not supposed to patch the Info.plist, but it should replace forceBoostOff with ke1 in AppleGVA binary.

If you run lldb on VDADecoderChecker and then use `memory find` to find something like `preferredBGRA` you will see something close to the following in hexdump:

```
00000000000ddb18                        db         "preferredBGRA", 0           
00000000000ddb26                        db         "", 0
00000000000ddb27                        db         "", 0
00000000000ddb28                        db         "", 0
00000000000ddb29                        db         "", 0
00000000000ddb2a                        db         "", 0
                                    aForceboostoff:
00000000000ddb2b                        db         "forceBoostOff", 0           ;this one should be replaced by ke1
                                    aInterlacedoff:
00000000000ddb39                        db         "interlacedOff", 0          
```

**Comment by vit9696** [comment]
Ugh, just realised what the issue is. It is a CFString, not a C string, which makes it have a size. As a result even after I patch the underlying content to be shorter, it still fails to find the value, because it is remains 13 symbols long instead of 3, and due to dyld shared cache having different string offsets the actual location will be very uneasy to find.

I am afraid the best approach for nvidia is to use a 14,2 mac model. But I have an idea to try patching board-id in AppleGVA itself. If it works one could select the model for AppleGVA but not for the rest of the system. Give it a try? Same flags (`shikigva=48`), and I need the debug log (`-shikidbg -liludbg`) with *Shiki* output in it as well. The last log was Lilu-only.

[2.1.3 (DEBUG) r2.zip](https://github.com/vit9696/Shiki/files/1489366/2.1.3.DEBUG.r2.zip)

**Comment by esetnik** [comment]
Thanks for all your work on this!

<img width="548" alt="screen shot 2017-11-20 at 6 41 02 pm" src="https://user-images.githubusercontent.com/664434/33047194-7fd3fa28-ce22-11e7-986c-85436a5d8d14.png">
[shiki.log](https://github.com/vit9696/Shiki/files/1489503/shiki.log)

**Comment by vit9696** [comment]
Well, the log looks to me (at least the stuff that is present in it). Did this actually work for you?

**Comment by esetnik** [comment]
No it doesn't work unfortunately. Are you expecting more output in the logs? The logs I provided are after a run of VDADecoderCheck. The output is still `AVDCreateGPUAccelerator: Error loading GPU renderer`

**Comment by vit9696** [comment]
Yes, I did expect more output, but the issue is that most likely macOS eats a large amount of them.
I think that you might have dyld shared cache invalidated after manually patching AppleGVA.
Consider disabling Shiki, rebuilding the cache, and trying again. Or maybe use a clean os. I do not see a reason for this to fail.
If it still fails I guess I will try to check it out tomorrow myself under a debugger.

**Comment by esetnik** [comment]
Thanks again for digging deeper. Just to make sure I did the following:
1. Remove Shiki.kext and reboot
2. Ran
```
sudo su
update_dyld_shared_cache -force
```
3. Put back Shiki.kext and reboot

I did notice something curious in the Lilu logs. Not sure if it's related.

```
2017-11-20 21:36:41.102525-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) patch for /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox in 7FFF33B88000 7FFF33F01000
2017-11-20 21:36:41.102531-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) done reading patches for 4962E
2017-11-20 21:36:41.102535-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) patch for /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox in 7FFF33B88000 7FFF33F01000
2017-11-20 21:36:41.102540-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) done reading patches for 49683
2017-11-20 21:36:41.102544-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) patch for /System/Library/PrivateFrameworks/AppleGVA.framework/Versions/A/AppleGVA in 7FFF3723E000 7FFF37321000
2017-11-20 21:36:41.102548-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) done reading patches for D19BE
2017-11-20 21:36:41.102552-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) patch for /System/Library/PrivateFrameworks/AppleGVA.framework/Versions/A/AppleGVA in 7FFF3723E000 7FFF37321000
2017-11-20 21:36:41.102556-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) done reading patches for C7D2C
2017-11-20 21:36:41.436324-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found a possible match for 0 of 2020202020202020
2017-11-20 21:36:41.436329-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found a possible match for 1 of 2020202020202020
2017-11-20 21:36:41.436334-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) failure not matching 2 of 10000434E435600 to expected 2020202020202020
2017-11-20 21:36:44.112864-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found a possible match for 0 of 3D20657079742074
2017-11-20 21:36:44.112869-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found a possible match for 1 of 4C5F454D41524620
2017-11-20 21:36:44.112874-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found a possible match for 2 of 4553555F4C455645
2017-11-20 21:36:44.112877-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found a possible match for 3 of A415441445F52
2017-11-20 21:36:44.112884-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found what we are looking for 62 6F 61 72 64 2D 69 64
2017-11-20 21:36:44.112888-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) restored write permssions
2017-11-20 21:36:44.194331-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found a possible match for 0 of 2020202020202020
2017-11-20 21:36:44.194336-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found a possible match for 1 of 2020202020202020
2017-11-20 21:36:44.194340-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found a possible match for 2 of 2020202020202020
2017-11-20 21:36:44.194343-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found a possible match for 3 of 2020202020202020
2017-11-20 21:36:44.194351-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) found what we are looking for 0 6B 65 31 0 FF FF FF
2017-11-20 21:36:44.194355-0500  localhost kernel[0]: (kernel) Lilu:    user @ (DBG) restored write permssions
```

**Comment by vit9696** [comment]
Hm, sorry, just realised that I gave you the wrong boot arg. Forgot that you have nvidia 1080, should be `shikigva=60` of course (4 for compatible renderer, 8 for vda whitelist, 16 to fix iTunes crashes, and 32 to replace the board id).

**Comment by esetnik** [comment]
It is working now as far as I can tell. I have the same behavior as manual GVA patch.

**Comment by vit9696** [comment]
Good. Now let's get that chromium issue resolved. Please tell me whether the hacks are actually needed (and work) in Shiki for chromium/chrome.

**Comment by esetnik** [comment]
@vit9696 FYI hardware decoding stopped working when I updated to 10.13.2.

**Comment by vit9696** [comment]
@esetnik hi, ugh, the code does not look like it changed anyhow.
Please create a new issue and attach a debug log with the latest Shiki.
Also, I may want the output of VDADecoderChecker.

**Comment by originalmagneto** [comment]
Hi, my config is similar, i7 7700 (non-k), GTX1060 as primary (DP as output), but I cant get QuickSync and hw encode/decode to work. Attaching my configs output files from relevant sources + my EFI folder. Can someone give me advice on how to enable HW encode/decode with my config? Thanks!

[report_Clover_EFI.zip](https://github.com/vit9696/Shiki/files/1748782/report_Clover_EFI.zip)
