### ISSUE TITLE
Some progress on watching Netflix HTML 5 video in Safari

### ISSUE THREAD

**Issue by 43n79w** [vit9696/Shiki#15]
I'm able to play Netflix HTML 5 videos in Safari on High Sierra in such a way that the audio plays perfectly but instead of an actual picture I get a green screen. This happens when setting `shikigva=2` with my properly configured Nvidia discrete GPU/Intel offline accelerator setup. If I omit this boot argument, then I get a Netflix error. If I omit this boot argument and don't have Shiki enabled or properly configured, then I get a prompt to install Silverlight.

The consensus seems to be that Safari's use of Encrypted Media Extensions for services like Netflix or Amazon Prime Video is somehow incompatible with Hackintoshes. But is it really the DRM which is incompatible or is there some other misconfiguration that just happens to cause video acceleration problems with respect to Safari? Perhaps it's related to Safari's sandboxing?

I was looking through the IOKit properties that Safari reads for DRM and it looks like properly configured Hackintoshes should have all the ones that Safari attempts to read. See [here](https://github.com/WebKit/webkit/commit/b7650a594d99850fe84d7d5b65d775641cf84605#diff-f84c348627ecbbe9c75795c6997da5eb) for a start.

**Comment by vit9696** [comment]
Hi, there is nothing new for me here unfortunately. It is a misconfiguration (as in missing IGPU DRM certificates), but I doubt anything could be done to it without proper knowledge and a lot of time.
