### ISSUE TITLE
hardware decoding hang after wake up

### ISSUE THREAD

**Issue by fRzzy** [vit9696/Shiki#16]
my hack is on Z170 chipset + i3 6100T CPU + Nvidia GTX 1050Ti GPU

hardware decoding currently work with Safari and QuickTime (not Chrome - even whitelisted)

after wake up from sleep, anything that try to use hardware decoding just not responding, QuickTime won't open (need to Force Quit), Safari show loading icon forever in YouTube (the browser itself works, videos won't play)

I'm not sure if this is Shiki problem or not, can you try to reproduce?

**Comment by vit9696** [comment]
Please use the support forums for help requests.
