### ISSUE TITLE
Da Vinci resolve processes whitelist request

### ISSUE THREAD

**Issue by xelanaiznac** [vit9696/Shiki#19]
<img width="779" alt="schermata 2017-12-16 alle 18 39 18" src="https://user-images.githubusercontent.com/6823633/34072945-78b54850-e290-11e7-8ddd-991b1c067573.png">
hi @vit9696, how are you?
thank you for your time and efforts helping me and a lot of people with your solutions. I don't know if I'm writing in the right place but here https://github.com/vit9696/Shiki/issues/5
on the 10th of october you wrote that we can ask for more processes paths.
I would like to ask you as @emiliogonzalezjunior did to add davinciresolve to the processes whitelist please.
thank you in advance

**Comment by vit9696** [comment]
Hi, Add the path to [Patches.plist](https://github.com/vit9696/Shiki/blob/master/Resources/Patches.plist) in a similar way to other tools, then rebuild Shiki, and ensure that the acceleration works for you.
Afterwards give me the changes, and I will include them in the latest update.
Thanks =)

**Comment by emiliogonzalezjunior** [comment]
Hi @xelanaiznac I submitted today a change in the patches.plist with the inclusion of Davinci Resolve. I've been running my own compiled version of shiki for 1 month and Davinci is working as expected. The only thing that I missing now is the airplay (only works without hardware acceleration), unfortunately I tried a lot of paths in the whitelist but none of them works with airplay. @vit9696, do you have any suggestion of paths that i should try and test? As always, thanks @vit9696 for your hard work.

**Comment by xelanaiznac** [comment]
Hi. Can you provide me please the modified Shiki kext?
Are you sure airplay is not working? Are you using shikigva=60 bootargs?




Alex Canzian
+393473300809

**Comment by xelanaiznac** [comment]
Ok, i have been successful on compiling Shiki kext with your modified patches, thank you.
Regarding airplay, here some news:
i have a MacBook Pro retina mid 2015 dual gpu and usually my macbook gives me a gt:0,25 ghz speed for my idle igpu (intel power gadget info)
When I enable airplay mirroring to my Apple TV, intel power gadget gives me the gt:0,20 ghz value (lower than idle!)

So, I’m just saying that maybe airplay mirroring is using intel gpu but we cannot find confirm using intel power gadget app in our hacks.
Do you understand what I mean?




Alex Canzian
+393473300809

**Comment by vit9696** [comment]
I will upload a new release some while later, there are too few changes for the time being.
As for AirPlay, unfortunately I have no clue.
