### ISSUE TITLE
iTunes Extras

### ISSUE THREAD

**Issue by sinanziric** [vit9696/Shiki#2]
I am using osx Sierra 10.12.0 and after shiki installation in Clover EFI and after I've reset DRM I was able to play DRM Movies (Bought + Rented) ones. However I am unable to play any iTunes Extras. Is there any way around it.

Cheers. (btw Awesome kext) I have been waiting for years to play my movies on my hackintosh.

**Comment by vit9696** [comment]
Have never tried, but likely not I am afraid.

**Comment by sinanziric** [comment]
It looks like all streamed drm content cannot be played which is the reason why I can't play iTunes extras.  Even the movies, I have to download them first because I can't stream them.

**Comment by vit9696** [comment]
It is possible that streaming requires FairPlay 2. So it won't work, yes.
