### ISSUE TITLE
Will it work for Haswell-E CPU with Dedicated GPU ?

### ISSUE THREAD

**Issue by arifcatalyst** [vit9696/Shiki#21]
> Shiki-based solution for an unsupported CPU (e.g. Haswell Celeron E):
Hardware video decoding acceleration does not work with these CPUs and to boot you need to fake your CPUID.
Disable IGPU completely or rename it to some random name (e.g. IGFX) and install Shiki, it should work for you. It is not fully explored what preferences are needed but it is known that disabled hardware acceleration by AppleGVA plist editing/MacPro5,1 model setting helps to view HD movies sometimes.

After going through all posts in insanelymac,FAQs and discussions in tickets, I can't find a single case which pertains to my use-case. 

Is VDA possible for Haswell-E CPUs with Maxwell card ?

**Comment by vit9696** [comment]
Hi, if Haswell-E cpus have no IGPU (and from what I remember they do not), it is certainly not possible with an NVIDIA GPU after GT 2xx series. Newer AMD cards (4xx or 5xx) or older NVIDIA cards (2xx, 1xx, or 8xxx) may work, but I cannot give any promises.

**Comment by arifcatalyst** [comment]
> int nvAcceleratorParent::SetAccelProperties(nvAcceleratorParent* this) {
	int rendererId = 0;
	int rendererSubId = 0;
	int oclass = GetCardOclass(this);
	if (oclass <= 0x88B0) {
		if (oclass == 0x74B0) {
			rendererId = 0x1040002;
		} else if (oclass == 0x85B1) {
			rendererId = 0x1040008;
			rendererSubId = 1;
		} else {
			if (oclass != 0x86B1)
				return;
			rendererId = 0x1040008;
			rendererSubId = 2;
		}
		SetProperty(this, "IOVARendererID", &rendererId, 4LL);
		if (rendererSubId)
			SetProperty(this, "IOVARendererSubID", &rendererSubId, 4LL);
	} else if (oclass == 0x88B1) {
		rendererId = 0x1040004;
		SetProperty(this, "IOVARendererID", &rendererId, 4LL);
	} else if (oclass == 0x95B1 || oclass == 0x90B1) {
		rendererId = 0x1040008;
		rendererSubId = 3;
		SetProperty(this, "IOVARendererID", &rendererId, 4LL);
		SetProperty(this, "IOVARendererSubID", &rendererSubId, 4LL);
	}
}

As you see basically NVIDIA added a hack for iMac14,2 and similar with 6xx GPUs (oclass 0x95B1) by pretending that they are VP4 GPUs. So, injecting 0x1040008 for Maxwell GPUs did nothing but extend the same hack a little further. Since AppleGVA won't recognise any other value, you are pretty much bound to use one of those known IDs for Pascal cards as well.

One last note is that starting with 10.12.3 you need to recompile VDADecoderChecker, and starting with 10.12.4 few users reported that there are plist injection issues for their Maxwell GPUs.


Is something like possible by pretending VP6 GPUs to act like VP4 as discussed above ?

**Comment by vit9696** [comment]
No, even the hack mentioned above does not make the use of NVIDIA hardware decoder. It only adds a variable for AppleGVA to be able to passthrough stuff from IGPU hardware decoder to NVIDIA.

**Comment by vkedwardli** [comment]
@vit9696 does it mean that even with dedicated NVIDIA gpu (GTX1060 for example), IGPU must be enabled and only IGPU's processing is used for hardware accelerated decoding?

**Comment by vit9696** [comment]
Yes, exactly that.
