### ISSUE TITLE
Mistake in the FAQ?

### ISSUE THREAD

**Issue by evansan** [vit9696/Shiki#22]
```
defaults delete com.apple.coremedia
defaults delete com.apple.AppleGVA
sudo rm -rf /Users/Shared/SC\ Info
sudo defaults delete com.apple.coremedia
sudo defaults delete com.apple.AppleGVA
```
Line 1 2 and line 3 4  doing the same thing?
I get errors with line 3 4:
Domain (com.apple.coremedia) not found.
Defaults have not been changed.

Domain (com.apple.AppleGVA) not found.
Defaults have not been changed.

**Comment by vit9696** [comment]
Hi, I assume you meant lines 1, 2 and lines 4, 5.

They are not the same thing: the first ones delete user-local preferences, and the second ones delete global preferences.

There is no issue if you get an error, because it only means you have never written any preferences on your own.
