### ISSUE TITLE
shiki doesn't select shikigva flag

### ISSUE THREAD

**Issue by Gymnae** [vit9696/Shiki#25]
I have an i5 8400 with Intel UHD Graphics 630 as built in, used only for quick sync and as primary an Nvidia Geforce 1080.
With shikigva=60 I had acceleration in quicktime, but not in Firefox
without any flag, I have no acceleration at all. 
Is it thus still advisable to set a manual flag and which one should it be? 

Also, when I use shiki.kext, then my sleep won't work. The system wakes up immediately after haven fallen asleep

**Comment by vit9696** [comment]
https://github.com/vit9696/Shiki/blob/master/Shiki/kern_start.cpp#L18
Check this instruction out and see what actual flags do you need. Please reopen the issue if you think that Shiki misbehaves.

Immediate wake after sleep has nothing to do to Shiki, it is some of your USB devices (e.g. Bluetooth).
