### ISSUE TITLE
10.12.1 Beta 4 gives green screen.

### ISSUE THREAD

**Issue by D-an-W** [vit9696/Shiki#3]
Hi, I think you are already aware of this but just wanted to make sure.

Beta 3 was fine, Beta 4 I get sound but just a green screen (Have also reset DRM).

**Comment by vit9696** [comment]
Well, "beta" software. I think it depends on what configuration you have. Somebody worked it out [by editing the plist](http://www.insanelymac.com/forum/topic/312278-shiki-—-userspace-patcher/page-3#entry2298660). This is destructive, but I don't know much about beta.
In my opinion, it is best to wait.

**Comment by D-an-W** [comment]
I am happy to report v1.9.0 is working well again with 10.12.1 Beta 5
