### ISSUE TITLE
Two reboots when restating or in the first boot in 10.12.5

### ISSUE THREAD

**Issue by jktaurus8** [vit9696/Shiki#6]
When restarting or first boot the computer automatically reboots again at the apple boot logo. Without using Shiki kext with -shikigva boot flag computer starts normally.

**Comment by vit9696** [comment]
Hi, well, this is not something helpful. If you have kernel panics, post the crash logs with debug kexts (Lilu/Shiki) and keepsyms=1 in bootargs. Also, I don't know how -shikigva could affect anything when Shiki is removed @_@

**Comment by jktaurus8** [comment]
After deleting the current shiki kext and lilu kext then replaced it with the same version solved the problem. Thanks ..

**Comment by EricTheRed1** [comment]
I'm having a similar issue when I updated to 10.12.5.  Everything was fine in 10.12.4 and then updating caused a kernel panic after passing the login screen.  Deleting the shiki.kext files from the entire computer did not solve the issue either.  The only reason i was able to boot at all was by putting -shikioff in the boot flags.

**Comment by jktaurus8** [comment]
Delete lilu kext also !

**Comment by EricTheRed1** [comment]
Yes, I read your post but i've never even used the lilu kext.  I did check and It's not on my system

**Comment by jktaurus8** [comment]
If you are on a kabylake system make sure that FakeCPUId is added and check your graphics configuration (kext fakeid etc..)

**Comment by EricTheRed1** [comment]
hmmm....well i'm on Haswell.  I've always left my graphics configuration in the config.plist blank with no issues.

**Comment by jktaurus8** [comment]
The please post the kernal panic screenshot.

**Comment by EricTheRed1** [comment]
I got it working just fine.  Nowhere did it mention to use Lilu.kext

**Comment by jktaurus8** [comment]
You can use it , it contains graphics and other resources for hackintosh. This is up to you whether use it or not .
