### ISSUE TITLE
Not Working on 10.12.5 (16F73)

### ISSUE THREAD

**Issue by Hanger1** [vit9696/Shiki#7]
It freezes on latest update 10.12.5 (16F73) with IntelHD4600 (No other GPU installed).

**Comment by vit9696** [comment]
Read the FAQ.

**Comment by Hanger1** [comment]
I was using clover patch for freeze 48898BA8000000 > 90909090909090 it was working awesome.
I tried IntelGraphicsFixup.kext and Shiki.kext ... which is not preventing freeze
will you tell me whats new binary patch for 10.12.5 ?
