### ISSUE TITLE
Standby mode and hibernation sleep/wake modify CoreFP on disk

### ISSUE THREAD

**Issue by barijaona** [vit9696/Shiki#9]
I have noticed a problem for a time now, but I can now document it more precisely.
My hack sometimes reboot instead of waking from sleep. Afterwards, the CoreFP private framework inside the System folder is damaged.
````
$ codesign --verify /System/Library/PrivateFrameworks/CoreFP.framework 
/System/Library/PrivateFrameworks/CoreFP.framework: invalid signature (code or signature have been modified)
In architecture: x86_64
````

Comparing the CoreFP binary with the original one reveals the following on disk changes : 
- at offset 0x10039748, what should be 0xF4FEFFFF has been replaced by 0xF0FEFFFF
- at offset 0x24109816, what should be 0x01000000 0FA24889 has been replaced by 0xC2060200 90904889

I would expect that any patching made by Shiki would only affect caches and would never modify /System/Library/.

Some info about my current configuration : 
- macOS 10.12.6
- Clover v4200
- Lilu 1.1.7
- Shiki 2.0.5
- HibernationFixup 1.1.7
- CoreFP 2.13.16 (the one which goes with iTunes 12.7.0)

Note that the problem may appear even if hibernation is not used on the machine.

**Comment by barijaona** [comment]
By the way, where can we download the latest binaries of Lilu and Shiki ?

**Comment by barijaona** [comment]
Note also that the modification time of the damaged CoreFP binary remains unchanged.
So the problem can only be noticed through codesign or through a byte-by-byte comparison with the original.

**Comment by vit9696** [comment]
When Shiki is loaded this behaviour will be the correct one, once you reboot without Shiki the file will no longer report as damaged. The latest Lilu and Shiki are available on releases page on github.

**Comment by barijaona** [comment]
1/ I have reproduced the same situation, rebooted without Shiki and the file is still reported as damaged. At offset 0x10039748, what should be 0xF4FEFFFF has been replaced by 0xF0FEFFFF. So I think the issue should not be closed.

2/ The latest Lilu on the releases page is 1.1.7 (commit 0cb879d) while git logs refer to 1.1.8 and 1.2.0. Similarly, 2.0.6 appears in Shiki's Changelog.md but only 2.0.5 has been published.
All these tags haven't been pushed to Github so I am a bit confused about which combo is currently recommended. Should I stick to the published binaries or is it better to build from HEAD ?

**Comment by vit9696** [comment]
Well, mhm, the thing is 1 is not really replaced by Shiki… I see no such sequence.

As for 2.0.5 it was a bugged release that was immediately reverted and replaced by 2.0.6. It is normally a good idea to stick to published binaries. I would say that the current HEAD binaries should work just as good though.

I will leave the issue open, but I don't think it should happen, to be honest.

**Comment by barijaona** [comment]
At the time of writing, the latest binary versions available for download on your Github pages are : 
- Lilu 1.1.7
- Shiki 2.0.5
- AppleALC 1.1.4
- WhateverGreen 1.0.4

I suggest you upload at least recent versions of Lieu, Shiki and AppleALC

**Comment by vit9696** [comment]
What else would you like to suggest me? Impose a modern release cycle at your desire? Current binaries are latest, 1.2.0 and others are for devs only.

**Comment by barijaona** [comment]
Excuse me, I didn’t want to offend you. I just wanted to explain my surprise. 

I am perfectly able to compile kexts and I understand that there are work in progress you don’t want to expose to a large public.

What I find somewhat confusing and might be improved is the references used in your commit log. Wouldn’t it be better to specifically label some tags as “alpha” or “beta” ? It’s a bit surprising reading above that “2.0.5 was a bugged release”, while 2.0.5 is the latest downloadable binary. I guess I would have avoided a lot of useless questions if I had seen tags like ”2.1.0beta1”, “2.1.0beta2” and so on…

Just my two cents. I am just trying to be constructive and I thank you for your hard work which is extremely useful.

**Comment by vit9696** [comment]
I am afraid I confused you quite a bit. I mistook Shiki 2.0.5/2.0.6 with Lilu 1.1.1/1.1.3 release, because I did not realise anybody noticed the changelogs and the switch from 2.0.6 to 2.1.0. Sorry. Current 2.0.5 is more or less fine, at least it should not have any known issues.

The thing is that most of the changes are done locally and/or in private repos, and github is only used for upstreaming the source code, so I am afraid I won't make a better track of the changes. A lot of code was initially not planned to be opensourced inside Lilu in the first place, but since several other projects benefited from that, it happened, and therefore a major API break was imposed everywhere (thus effectively making me increase the minor version).
